# Generated by Django 4.0.6 on 2023-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200922_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название города'),
        ),
    ]
